# Generated by Django 3.1.4 on 2020-12-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201226_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('BS', 'BestSeller'), ('PP', 'Popular')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1),
        ),
    ]
