# Generated by Django 3.1.4 on 2020-12-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201230_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_default_address',
        ),
    ]
