# Generated by Django 3.1.4 on 2020-12-30 09:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=django_countries.fields.CountryField(default=3, max_length=2),
            preserve_default=False,
        ),
    ]
