# Generated by Django 3.1.4 on 2020-12-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coupon_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.AddField(
            model_name='refund',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.orderitem'),
            preserve_default=False,
        ),
    ]
