# Generated by Django 3.1.4 on 2020-12-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201230_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='customer',
        ),
        migrations.AddField(
            model_name='refund',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
