# Generated by Django 3.1.4 on 2021-01-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20210114_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PC', 'Processing'), ('BD', 'Being Delivered'), ('R', 'Received')], default='PC', max_length=2),
        ),
    ]
